import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";

const root = process.cwd();
const bridgeFile = path.join(root, "bridge", "server.mjs");
const envPath = path.join(root, "bridge", ".env");
if (!fs.existsSync(bridgeFile)) {
  console.error("bridge/server.mjs is missing. Reconstruct the TV Phone source first.");
  process.exit(1);
}
if (!fs.existsSync(envPath)) {
  const server = fs.readFileSync(bridgeFile, "utf8");
  const names = [...new Set([...server.matchAll(/process\.env\.([A-Z0-9_]+)/g)].map(m => m[1]))].sort();
  const token = crypto.randomBytes(32).toString("hex");
  const lines = ["# Generated by TV Phone. Keep this file private."];
  for (const name of names) {
    const upper = name.toUpperCase();
    let value = "";
    if (upper.includes("TOKEN") || upper.includes("SECRET")) value = token;
    else if (upper.includes("PORT")) value = "8787";
    else if (upper.includes("HOST") || upper.includes("BIND")) value = "0.0.0.0";
    lines.push(`${name}=${value}`);
  }
  fs.writeFileSync(envPath, lines.join("\n") + "\n", { mode: 0o600 });
  console.log("Created bridge/.env with a random bearer token.");
} else {
  console.log("bridge/.env already exists; leaving it unchanged.");
}
const ips = [];
for (const entries of Object.values(os.networkInterfaces())) {
  for (const item of entries ?? []) {
    if (item.family === "IPv4" && !item.internal && (/^10\./.test(item.address) || /^192\.168\./.test(item.address) || /^172\.(1[6-9]|2\d|3[01])\./.test(item.address))) ips.push(item.address);
  }
}
console.log(`Config: ${envPath}`);
if (ips.length) console.log(`LAN addresses: ${ips.join(", ")}`);
console.log("Next: npm run bridge:doctor");
